[build]
  # Build command - not needed for static site
  command = ""
  
  # Directory to publish
  publish = "public"

[build.environment]
  # Node.js version for any build processes
  NODE_VERSION = "18"

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.github.com;"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Specific caching for HTML files
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Specific caching for CSS and JS files
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  # SPA fallback (if needed in the future)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

[[redirects]]
  # GitHub repository redirect
  from = "/github"
  to = "https://github.com/nibertinvestments/DATA"
  status = 301

[[redirects]]
  # Direct download redirect
  from = "/download"
  to = "https://github.com/nibertinvestments/DATA/archive/refs/heads/main.zip"
  status = 301

# Form handling (if needed for contact forms in the future)
[forms]
  contact = true

# Function settings (for serverless functions if needed)
[functions]
  directory = "netlify/functions"
  
# Deploy contexts
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "staging"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-minify-html"
  
  [plugins.inputs]
    contexts = ["production"]